# Permalinks
permalink:           pretty

# Setup
title:               Algorithms for software engineers
tagline:             Theory and practical aspects
url:                 https://ira-dushar.github.io/algorithms/
paginate:            1
baseurl:             "https://ira-dushar.github.io/algorithms/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ira Dushar
  url:               https://ira-dushar.github.io/algorithms/
  email:             support@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ira-dushar/algorithms

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
